
title: Jake's Thoughts
email: peterjbg@uni.edu
description: "This is my blog where I will share my thoughts. A few things I'm passionate about: technology, sports, politics."
baseurl: "/blog"
url: "jdpeterman.github.io"
github_username:  jdpeterman


# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
